apiVersion: apps/v1
kind: Deployment
metadata: &id001
  annotations:
    type: development-container
  labels:
    app: olmp-test
    user: test
  name: olmp-test
  namespace: development
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: olmp-test
      user: test
  template:
    metadata: *id001
    spec:
      containers:
      - args:
        - service ssh start && /bin/bash&& while true;do sleep 10; done;
        command:
        - /bin/bash
        - -c
        image: 10.16.97.52:8433/library/cuda-caffe-ssh:debug
        imagePullPolicy: Always
        name: olmp-test
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 300Mi
            cpu: 200m
        volumeMounts:
        - mountPath: /data/
          name: nfs-file
      imagePullSecrets:
      - name: harbor-admin-secret
      volumes:
      - name: nfs-file
        nfs:
          path: /mnt/data/Users/test
          readOnly: false
          server: 10.16.97.52
