apiVersion: v1
kind: Service
metadata:
  annotations:
    type: development-container
  labels:
    app: olmp-test
    user: test
  name: olmp-test
  namespace: development
spec:
  type: NodePort
  ports:
  - nodePort: 31500
    port: 80
    targetPort: 22
  selector:
    app: olmp-test
    user: test
