apiVersion: v1
kind: Service
metadata:
  annotations:
    type: development-container
  labels:
    app: dev1
    user: iws
  name: dev1
  namespace: development
spec:
  type: NodePort
  ports:
  - nodePort: 31500
    port: 80
    targetPort: 22
  selector:
    app: dev1
    user: iws
