server:
  port: 8001
  servlet:
    context-path: /support

k8s:
  testPath: /root/.kube/config
  Path: /etc/restfulserver/mconfig

gitlab:
  token: "spoW2GvS96-zWtQEg32s"
  path: ./token

alg:
  namespace: default

dev:
  namespace: development

deployment:
  appAddress: http://10.16.97.52:30098/support/app
  taskAddress: http://10.16.97.52:30098/support/task

nginx:
  downloadAddress: http://10.16.97.52:30234/download

image:
  dockerHost: tcp://10.16.11.109:2375
  username: admin
  password: 123456
  repositoryAddress: 10.16.97.52:8433
  persistence: public
  tmp: tmp
  library: library




logging:
  config: /etc/restfulserver/logconfig.xml
  level:
    cn.jay.repository: trace


spring:
  application:
    name: restfulserver

management:
  security:
    enabled: false
    #prometheus+grafana+springboot2监控集成配置
  metrics:
    tags:
      applications: ${spring.application.name}
    export:
      prometheus:
        enabled: true
      jmx:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /metrics
      #prometheus+grafana+springboot2监控集成配置
